string sample_name 
string target_name
string task_name # 4 options are : PICK_UP, PLACE, RETURN_PICK_UP, RETURN_PLACE
---
bool success
---
int32 completed_precentages
# bool partial_success
int32 total_number_of_stages
